server:
  port: 8081

weather:
  url : http://api.openweathermap.org/data/2.5/weather
  apiKey : 73eef1b8900294857cf8521aea0abe3f
  lang: ru
  units : metric
spring:
  datasource:
    initialization-mode: always
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/weather
    username: postgres
    password: 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
springfox:
  documentation:
    swagger:
      v2:
        use-model-v3: true